# Generated by Django 4.1.2 on 2023-04-12 07:37

from django.db import migrations, models
import django.db.models.deletion
import flow.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('target', models.URLField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.organization')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('payload', models.JSONField()),
                ('image', models.ImageField(blank=True, max_length=512, upload_to=flow.models.Code.image_path)),
                ('zorder', models.IntegerField(default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='flow.application')),
            ],
            options={
                'ordering': ('zorder', 'name'),
            },
        ),
    ]
