# Generated by Django 4.1.2 on 2023-09-28 16:02

from django.db import migrations, models
import django.db.models.deletion
import flow.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Application name', max_length=128)),
                ('domain', models.URLField(help_text='Domain to validate endpoint URLs')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.organization')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128)),
                ('method', models.CharField(choices=[('HEAD', 'HEAD'), ('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('OPTIONS', 'OPTIONS'), ('TRACE', 'TRACE'), ('CONNECT', 'CONNECT')], default='GET', help_text='HTTP method to contact the endpoint', max_length=8)),
                ('target', models.URLField(help_text='Endpoint target URL (raw or template)')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Specific parameters to contact the endpoint (excluded credentials)')),
                ('application', models.ForeignKey(help_text="Endpoint's application", on_delete=django.db.models.deletion.RESTRICT, related_name='endpoints', to='flow.application')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('application', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=256)),
                ('payload', models.JSONField()),
                ('image', models.ImageField(blank=True, max_length=512, upload_to=flow.models.Code.image_path)),
                ('zorder', models.IntegerField(default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='codes', to='flow.application')),
            ],
            options={
                'ordering': ('zorder', 'name'),
                'unique_together': {('application', 'name')},
            },
        ),
    ]
