# Generated by Django 4.1.2 on 2023-04-12 08:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='target',
        ),
        migrations.AddField(
            model_name='application',
            name='domain',
            field=models.URLField(default='landercy.be', help_text='Domain to validate endpoint URLs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(help_text='Application name', max_length=128, unique=True),
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('target', models.URLField(help_text='Endpoint target URL (raw or template)')),
                ('application', models.ForeignKey(help_text="Endpoint's application", on_delete=django.db.models.deletion.RESTRICT, to='flow.application')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
