# Generated by Django 4.1.2 on 2022-11-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_code_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='target',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
