# Generated by Django 4.1.2 on 2023-09-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_alter_code_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='payload',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
