# Generated by Django 4.1.2 on 2023-04-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_endpoint_method_alter_code_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='parameters',
            field=models.JSONField(default=dict, help_text='Specific parameters to contact the endpoint (excluded credentials)'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='method',
            field=models.CharField(choices=[('HEAD', 'HEAD'), ('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('OPTIONS', 'OPTIONS'), ('TRACE', 'TRACE'), ('CONNECT', 'CONNECT')], default='GET', help_text='HTTP method to contact the endpoint', max_length=8),
        ),
    ]
