# Generated by Django 4.1.2 on 2023-09-30 07:29

from django.db import migrations
import encrypted_json_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0004_alter_code_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='credentials',
            field=encrypted_json_fields.fields.EncryptedJSONField(blank=True, default=dict, null=True),
        ),
    ]
