# Generated by Django 4.1.2 on 2023-04-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('flow', '0004_endpoint_parameters_alter_endpoint_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='endpoint',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(help_text='Application name', max_length=128),
        ),
        migrations.AlterField(
            model_name='code',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Specific parameters to contact the endpoint (excluded credentials)'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='code',
            unique_together={('application', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='endpoint',
            unique_together={('application', 'name')},
        ),
    ]
