# Generated by Django 4.1.2 on 2023-10-01 09:36

from django.db import migrations, models
import django.db.models.deletion
import encrypted_json_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0005_application_credentials'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='endpoint',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='application',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='code',
            name='endpoint',
        ),
        migrations.AddField(
            model_name='application',
            name='forward_endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='flow.endpoint'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='credentials',
            field=encrypted_json_fields.fields.EncryptedJSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='application',
        ),
    ]
