# Generated by Django 4.1.2 on 2023-10-01 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('flow', '0006_alter_endpoint_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='organization',
            field=models.ForeignKey(default='09114bbb-c7cb-4011-9fd4-6db41d06e7a5', on_delete=django.db.models.deletion.RESTRICT, to='core.organization'),
            preserve_default=False,
        ),
    ]
