# Generated by Django 4.1.2 on 2023-10-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('flow', '0007_endpoint_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='endpoint',
            unique_together={('organization', 'name')},
        ),
    ]
