# Generated by Django 4.1.2 on 2023-10-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0008_alter_endpoint_name_alter_endpoint_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='auto_post',
            field=models.BooleanField(default=False),
        ),
    ]
