# Generated by Django 4.1.2 on 2023-10-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0012_code_code_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code_type',
            field=models.CharField(choices=[('QR', 'QR'), ('QR-EPC', 'QR-EPC'), ('QR-DGC', 'QR-DGC'), ('CODABAR', 'CODABAR'), ('CODE128', 'CODE128'), ('CODE39', 'CODE39'), ('EAN', 'EAN'), ('EAN13', 'EAN13'), ('EAN13-GUARD', 'EAN13-GUARD'), ('EAN14', 'EAN14'), ('EAN8', 'EAN8'), ('EAN8-GUARD', 'EAN8-GUARD'), ('GS1', 'GS1'), ('GS1_128', 'GS1_128'), ('GTIN', 'GTIN'), ('ISBN', 'ISBN'), ('ISBN10', 'ISBN10'), ('ISBN13', 'ISBN13'), ('ISSN', 'ISSN'), ('ITF', 'ITF'), ('JAN', 'JAN'), ('NW-7', 'NW-7'), ('PZN', 'PZN'), ('UPC', 'UPC'), ('UPCA', 'UPCA')], default='QR', help_text='Type of code', max_length=16),
        ),
        migrations.AlterField(
            model_name='code',
            name='payload',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
