# Generated by Django 4.1.2 on 2023-10-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0013_alter_code_code_type_alter_code_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='repeat_scan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='scan_delay',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='code',
            name='code_type',
            field=models.CharField(choices=[('QR', 'QR'), ('QR-JSON', 'QR-JSON'), ('QR-EPC', 'QR-EPC'), ('QR-DGC', 'QR-DGC'), ('codabar', 'CODABAR'), ('code128', 'CODE128'), ('code39', 'CODE39'), ('ean', 'EAN'), ('ean13', 'EAN13'), ('ean13-guard', 'EAN13-GUARD'), ('ean14', 'EAN14'), ('ean8', 'EAN8'), ('ean8-guard', 'EAN8-GUARD'), ('gs1', 'GS1'), ('gs1_128', 'GS1_128'), ('gtin', 'GTIN'), ('isbn', 'ISBN'), ('isbn10', 'ISBN10'), ('isbn13', 'ISBN13'), ('issn', 'ISSN'), ('itf', 'ITF'), ('jan', 'JAN'), ('nw-7', 'NW-7'), ('pzn', 'PZN'), ('upc', 'UPC'), ('upca', 'UPCA')], default='QR', help_text='Type of code', max_length=16),
        ),
    ]
