# Generated by Django 4.1.2 on 2023-10-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0014_application_repeat_scan_application_scan_delay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ajax_mode',
            field=models.BooleanField(default=False),
        ),
    ]
