# Generated by Django 4.1.2 on 2023-10-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0015_application_ajax_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='scan_delay',
            field=models.FloatField(default=2.5),
        ),
    ]
