# Generated by Django 4.1.2 on 2022-11-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_application_target'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'ordering': ('zorder', 'name')},
        ),
        migrations.AddField(
            model_name='code',
            name='zorder',
            field=models.IntegerField(default=0),
        ),
    ]
