# Generated by Django 4.1.2 on 2022-11-12 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pki.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('public_key', models.FileField(blank=True, upload_to=pki.models.Certificate.organization_public_path)),
                ('private_key', models.FileField(blank=True, upload_to=pki.models.Certificate.organization_private_path)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
