# Generated by Django 4.1.2 on 2022-11-12 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(through='core.OrganizationMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
