# Generated by Django 4.1.2 on 2022-11-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationmembership',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='organizationmembership',
            unique_together={('user', 'organization')},
        ),
    ]
